@startuml



    |automatisch|
    start
    if (Provider) then (SoccerNet)
        :Lokale Video-Suche;
    else (YouTube)
        |manuell|
        :Online-Video-Suche;
    endif
    |automatisch|
    :Video-Download;
    if (Provider) then (SoccerNet)

    else (YouTube)
      :OCR Aligning;
    endif
    :Aktionssuche;
    |manuell|
    :Integritätscheck;
    |automatisch|
    stop


@enduml

