@startmindmap

* HAR

** Early Fusion
*** Two-Stream-Modell
** Late Fusion
*** Conv Pooling
*** 2D-CNN + LSTM
** Slow Fusion
*** 3D-Convolution
*** Faktorisierte 3D-Convolution
**** 2+1D-Convolution
**** Separierbare Convolution

@endmindmap