@startuml
skinparam monochrome true


cloud "Cloud\nStorage" as COMET {

}




package "Framework" {

    component [DataModule] {
        () "Database" as Database
    }


    component [TrainModule] {
        () "HAR-Model" as Net
        () "Batch" as TrainBatch
    }


    component [EvalModule] {
        () "Batch" as EvalBatch
        () "Report" as Report
        () "Checkpoints" as Checkpoints
        () "Metrics"
    }

    DataModule -> TrainBatch : sample
    DataModule --> EvalBatch : sample

    TrainModule --> Report : log
    TrainModule --> Checkpoints : log
    TrainModule --> Metrics : log

    EvalModule --> Database : verify
    EvalModule -right-> COMET : upload

}

COMET -> Framework : reproduce



@enduml