@startuml

state "Benchmark" as Phase1
state "Hparam-Optimierung" as Phase2
state "Verkleinerung" as Phase3
state "Fine-Tuning" as Phase4

[*] -> Phase1
Phase1 -> Phase2
Phase2 -> Phase3
Phase3 -> Phase4
Phase4 -> [*]

Phase1 : 1. Initialisierung
Phase1 : 2. Transfer-Learning
Phase1 : 3. Verifikation
Phase2 : 1. Grid-Suche
Phase2 : 2. Transfer Learning
Phase3 : 1. Analyse + Entfernen v. Klassen
Phase3 : 2. Transfer-Learning
Phase3 : 3. Verifikation
Phase4 : 1. Manuelle Anpassung
Phase4 : 1. Label Smoothing
Phase4 : 1. Multi-Grid


@enduml