@startuml


concise "zeitliche Action Detection" as AD
robust "Action Recognition" as AR
concise "Feature-Aggregation" as FA
concise "Feature-Extraktion" as FE




@0
FE is Chunk
FA is Clip
AR is Background
AD is {hidden}


@16
FE is Chunk

@32
FE is Chunk

@48
FE is Chunk

@64
AD is Goal
FE is Chunk
FA is Clip
AR is Goal

@80
FE is Chunk

@96
FE is Chunk

@112
FE is Chunk

@128
FE is Chunk
FA is Clip

@144
FE is Chunk

@160
FE is Chunk

@176
FE is Chunk

@192
FE is Chunk
FA is Clip
AR is Background
AD is {hidden}



@enduml