@startuml
rectangle Framework {

usecase Inference as "
Inference
--
Klassifikation neuer,\nnicht-annotierter Videos
..Ergebnis..
Menge an Tupeln:\n(Intervall, Klassen)"

usecase Training as "
Training
--
Optimierung eines\nDeep Learning Modells\n mit annotierten Videos
..Ergebnis..
Optimierte Modell-Gewichte,\nScore- und Fehler\npro Beispiel"

usecase Post as "
Post-Processing
--
Manueller Abgleich der\n Trainingsbeispiele mit großem\nFehler, Beheben von Datenfehlern
..Ergebnis..
Angepasste Datenbank"

(Post) <.. (Scores und\n Fehler laden) : include
(Post) <.. (Datenbank laden): include

(Training) <.. (Datenbank laden) : include
(Training) <.. (Model &\n Modell-Gewichte\nladen) : include


(Inference) <.. (Model &\n Modell-Gewichte\nladen) : include
(Inference) <.. (Video Upload) : include
}

:User: -down-> (Inference)
:Data\nScientist: as Scientist
Scientist -down-> (Training)
:Annotator: as Annotator
Annotator -down-> (Post)

@enduml
