@startuml

usecase Data as "
Data-Engineering
--
Erstellung des Datensets\nbasierend auf Feeds und\nVideos
..Ergebnis..
Initiale Datenbank\n(JSON)"

usecase Inference as "
Inferenz
--
Klassifikation neuer,\nnicht-annotierter Videos
..Ergebnis..
Menge an Tupeln:\n(Intervall, Klassen)"

rectangle Framework {

usecase Training as "
Training
--
Optimierung eines\nDeep Learning Modells\n mit annotierten Videos
..Ergebnis..
Optimierte \n Modell-Gewichte &\n Fehlerreport"

usecase Post as "
Verifikation
--
Manueller Abgleich \n anhand auffälliger Samples &\nBeheben von Datenfehlern
..Ergebnis..
Angepasste Datenbank"

(Post) <.. (Fehlerreport\nladen) : include
(Post) <.. (Datenbank\nladen): include

(Training) <.. (Datenbank\nladen) : include
(Training) <.. (Model &\n Modell-Gewichte\nladen) : include


(Inference) <.. (Model &\n Modell-Gewichte\nladen) : include
}

:Endnutzer: --> (Inference)
:Data\nScientist: as Scientist
Scientist --> (Training)
:Annotator: as Annotator
Annotator --> (Post)
Annotator --> (Data)
(Inference) <.. (Video Upload) : include


@enduml
